spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stujob
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  type-aliases-package: com.js.pojo
#  mapper-locations: classpath:mapper/*.xml